Repository Wanted-Pre-Onboarding-Team-8/wanted-pre-onboarding-movie-trailer, pull requests merged in 2022-09, with the labels that each got.

#6 [#4] modify: 불필요한 파일 삭제 및 적절치 않은 export 방식 수정
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/index.js
  src/style/GlobalStyle.jsx
  src/style/media.js
  src/style/reset.js
Labels: modify

#12 Fix/#10/modify folder fix error
  public/index.html
  src/App.jsx
  src/consts/route.js
  src/index.js
  src/pages/Detail.jsx
  src/pages/Home.jsx
  src/pages/NowPlaying.jsx
  src/pages/Search.jsx
  src/pages/TopRated.jsx
  src/pages/UpComing.jsx
  src/pages/index.js
  src/style/media.js
  src/style/reset.js
Labels: bug, modify

#9 Modify/#8/index.html 없는 파일 참조하고 있는 코드 삭제 및 수정
  .github/ISSUE_TEMPLATE/template.md
  public/index.html
Labels: modify

#18 [#16] fix: file name problem
  .eslintrc
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.jsx
  src/apis/.empty
  src/apis/base.js
  src/components/.empty
  src/components/Common/Card.jsx
  src/components/Common/index.js
  src/components/SearchForm.jsx
  src/components/index.js
  src/consts/.empty
  src/consts/index.js
  src/consts/net.js
  src/consts/route.js
  src/index.js
  src/pages/.empty
  src/pages/Detail.jsx
  src/pages/Home.jsx
  src/pages/NowPlaying.jsx
  src/pages/Search.jsx
  src/pages/TopRated.jsx
  src/pages/UpComing.jsx
  src/pages/index.js
  src/style/GlobalStyle.jsx
  src/style/media.js
  src/style/reset.js
Labels: bug

#22 [#21] modify: Card 컴포넌트에서 props 받아오는 코드 추가, 디자인 변경
  src/components/Common/Card.jsx
  src/components/Common/index.js
  src/components/SearchForm.jsx
  src/components/index.js
  src/pages/Detail.jsx
  src/pages/Home.jsx
  src/pages/NowPlaying.jsx
  src/pages/Search.jsx
  src/pages/TopRated.jsx
  src/pages/UpComing.jsx
Labels: modify

#36 [#35] feat: 공통 레이아웃 컴포넌트 구현
  src/App.jsx
  src/components/common/Layout.jsx
  src/components/common/index.js
Labels: enhancement

#39 [#7] feat: Now Playing 페이지 구현 및 Card 컴포넌트 스타일링
  src/apis/movie.js
  src/components/NowPlaying/NowPlayingItem.jsx
  src/components/NowPlaying/index.js
  src/components/common/Card.jsx
  src/components/common/Header.jsx
  src/components/index.js
  src/pages/NowPlaying.jsx
  src/style/GlobalStyle.jsx
  src/style/colors.js
Labels: enhancement

#44 [#42] feat: ScrollToTopButton 컴포넌트 구현
  src/components/common/Layout.jsx
  src/components/common/ScrollToTopButton.jsx
  src/components/common/index.js
Labels: enhancement

#45 [#25] feat: popular 페이지 구현
  .github/ISSUE_TEMPLATE/template.md
  package-lock.json
  public/index.html
  src/apis/movie.js
  src/components/Home/PopularList.jsx
  src/components/Home/index.js
  src/components/common/Card.jsx
  src/components/common/CardSkeleton.jsx
  src/components/common/index.js
  src/components/index.js
  src/consts/image.js
  src/consts/index.js
  src/consts/net.js
  src/consts/queryKey.js
  src/hooks/index.js
  src/hooks/queries/index.js
  src/hooks/queries/useNowPlayingMoviesQuery.js
  src/hooks/queries/usePopularMoviesQuery.js
  src/hooks/queries/useTopRatedMoviesQuery.js
  src/hooks/queries/useUpcomingMoviesQuery.js
  src/hooks/useIntersection.js
  src/pages/Home.jsx
  src/style/colors.js
Labels: enhancement

#49 [#46] refactor: Now Playing 페이지 리팩토링
  package-lock.json
  src/components/NowPlaying/NowPlayingItem.jsx
  src/components/NowPlaying/NowPlayingList.jsx
  src/components/NowPlaying/index.js
  src/pages/NowPlaying.jsx
Labels: refactor

#50 [#15] feat: upcoming 페이지 구현
  src/components/UpComing/UpComingItem.jsx
  src/components/UpComing/index.js
  src/components/common/ScrollToTopButton.jsx
  src/components/index.js
  src/consts/index.js
  src/hooks/index.js
  src/hooks/queries/useUpcomingMoviesQuery.js
  src/pages/UpComing.jsx
Labels: enhancement

#56 [#55] modify : Detail 스타일 변경
  package-lock.json
  src/components/Detail/Detail.jsx
  src/components/Detail/DetailTab.jsx
  src/style/GlobalStyle.jsx
Labels: modify
